// CRP RRBs XV — Office Assistant (Multipurpose) — Preliminary Examination.
// Exam structure verified against the official IBPS notification (CRP-RRBs-XV, section D, p.20):
//   Reasoning 40 Q / 40 marks / 25 min, Numerical Ability 40 Q / 40 marks / 20 min,
//   total 80 Q / 80 marks / 45 min, separately timed tests, 0.25 negative marking,
//   candidates must clear the cut-off in BOTH tests.
// The chapter list below is the preparation checklist (IBPS does not publish a chapter-wise list).

export const EXAM = {
  id: 'rrb-xv-oa-prelims',
  name: 'CRP RRBs XV — Office Assistant (Multipurpose)',
  stage: 'Preliminary Examination',
  window: 'November / December 2026 (tentative, per IBPS notification)',
  negativeMark: 0.25,
  sections: [
    { subject: 'reasoning', name: 'Reasoning', questions: 40, marks: 40, minutes: 25 },
    { subject: 'numerical', name: 'Numerical Ability', questions: 40, marks: 40, minutes: 20 },
  ],
  source: 'https://www.ibps.in/wp-content/uploads/CRP-RRBs-XV-notification.pdf',
}

// Subjects are data so future modules (GA, Computer, English, Mains) can be added without touching the core.
export const SUBJECTS = [
  { id: 'reasoning', name: 'Reasoning Ability', short: 'Reasoning', icon: '🧠', color: 'violet' },
  { id: 'numerical', name: 'Numerical Ability', short: 'Numerical', icon: '🔢', color: 'sky' },
]

const t = (id, subject, name, priority, subtopics, notes) => ({ id, subject, name, priority, subtopics, notes })

export const TOPICS = [
  // ---------------- Reasoning ----------------
  t('inequality', 'reasoning', 'Inequality', 'high',
    ['Direct Inequality', 'Coded Inequality', 'Mathematical Inequality', 'Statement-Based Inequality'],
    ['Read the chain between the two elements only — ignore the rest.',
      'Same direction signs (>, ≥, =) ⇒ definite relation; opposite signs anywhere in the path ⇒ no relation.',
      'Result is strict (>) if at least one strict sign appears, “=” only if every sign is “=”, otherwise ≥.',
      'Either–or applies when both conclusions fail, share the same two elements and together cover ≥ (i.e. “>” and “=”).']),
  t('syllogism', 'reasoning', 'Syllogism', 'high',
    ['Basic Syllogism', 'Statement and Conclusion', 'Possibility Cases', 'Either/Or Cases', 'Coded Syllogism'],
    ['Draw the minimum (basic) Venn diagram first; a conclusion follows only if it is true in EVERY possible diagram.',
      'All + All = All; All + No = No; Some + All = Some; Some + No = Some-not.',
      '“Some A are B” ⇒ “Some B are A” (conversion). “All A are B” ⇒ “Some B are A”.',
      'Possibility follows when it is not contradicted by the statements (and not already certain).',
      'Either–or: “Some X are Y” + “No X is Y” when neither is definite.']),
  t('coding-decoding', 'reasoning', 'Coding-Decoding', 'high',
    ['Letter Coding', 'Number Coding', 'Alphanumeric Coding', 'Coded Relationships', 'New-Pattern Coding'],
    ['Memorise EJOTY (5,10,15,20,25) for instant letter positions.',
      'Opposite letter pairs sum to 27: A↔Z, B↔Y, M↔N.',
      'For sentence codes, find the word common to two sentences — its code is the common code.',
      'Check shift (+1, −2…), reversal and opposite-letter patterns in that order.']),
  t('blood-relations', 'reasoning', 'Blood Relations', 'high',
    ['Direct Blood Relations', 'Family Tree', 'Coded Blood Relations', 'Generation-Based Questions'],
    ['Draw a family tree: generations vertical, couples horizontal (=), siblings with a line.',
      'Mark gender with +/− as soon as it is known; never assume gender from a name.',
      'Father’s/mother’s brother = uncle, their sister = aunt; brother’s son = nephew.']),
  t('direction-sense', 'reasoning', 'Direction & Distance', 'high',
    ['North, South, East, West', 'Left/Right Turns', 'Distance Calculation', 'Direction-Based Coding', 'Shortest Distance'],
    ['Facing North: right = East, left = West. Turning right is clockwise.',
      'Track net East–West and North–South displacement separately.',
      'Shortest distance = √(x² + y²); common triples 3-4-5, 6-8-10, 5-12-13, 8-15-17.']),
  t('order-ranking', 'reasoning', 'Order & Ranking', 'high',
    ['Rank from Left/Right', 'Rank from Top/Bottom', 'Total Number of Persons', 'Position Interchange', 'Ranking Comparison'],
    ['Total = rank from left + rank from right − 1.',
      'Persons between two people (non-overlapping) = Total − (L₁ + R₂).',
      'After interchange, the new position of one person gives the total directly.']),
  t('alphanumeric-series', 'reasoning', 'Alphanumeric Series', 'medium',
    ['Number Series', 'Letter Series', 'Alpha-Numeric Series', 'Position-Based Questions', 'Counting/Arrangement Questions'],
    ['“k-th to the right of the m-th from left” = element at position m + k from left.',
      'For “immediately preceded by X and followed by Y” scan each element and check both neighbours.',
      'Write position numbers above long series before solving.']),
  t('linear-seating', 'reasoning', 'Linear Seating Arrangement', 'high',
    ['Single row facing North', 'Single row facing South', 'Double row', 'Mixed facing'],
    ['Start with definite clues (ends, fixed positions), then clues that create few cases.',
      'Facing North: right of a person is your right; facing South it is reversed.',
      'Draw all possible cases side by side and eliminate with negative clues.']),
  t('circular-seating', 'reasoning', 'Circular Seating Arrangement', 'high',
    ['Facing centre', 'Facing outside', 'Mixed facing', 'Square/Rectangular Seating Arrangement'],
    ['Facing centre: left is clockwise, right is anticlockwise.',
      'Fix one person anywhere — circular arrangements have no ends.',
      'In n seats, “k-th to the left” equals “(n − k)-th to the right”.']),
  t('floor-puzzle', 'reasoning', 'Floor Puzzle', 'high',
    ['Floor-Based Puzzles', 'Flat/Floor with variables'],
    ['Number floors bottom-up (1 = lowest) unless told otherwise.',
      '“Above” is not “immediately above”. Note odd/even floor constraints early.']),
  t('box-puzzle', 'reasoning', 'Box Puzzle', 'high',
    ['Box-Based Puzzles', 'Stacked boxes with colours/items'],
    ['Same logic as floor puzzles: box 1 is the bottom-most.',
      'Count boxes between carefully: “two boxes between” means positions differ by 3.']),
  t('scheduling-puzzle', 'reasoning', 'Scheduling Puzzle', 'high',
    ['Month-Based Puzzles', 'Day/Date-Based Puzzles', 'Scheduling Puzzles'],
    ['List months/days in order with the number of days (30/31) where dates matter.',
      '“Before/after” clues create ranges; combine them to fix positions.']),
  t('misc-puzzles', 'reasoning', 'Miscellaneous Puzzles', 'medium',
    ['Comparison-Based Puzzles', 'Person–Profession–Place Puzzles', 'Age-Based Puzzles', 'Selection/Grouping Puzzles', 'Mixed-Variable Puzzles'],
    ['Comparison: build a chain from greatest to smallest using every clue.',
      'Grid puzzles: make a table (person × attribute) and tick/cross as you go.']),
  t('misc-reasoning', 'reasoning', 'Miscellaneous Reasoning', 'medium',
    ['Analogy', 'Classification', 'Odd One Out', 'Venn Diagrams', 'Word-Based Questions', 'Number-Based Questions', 'Decision Making', 'Basic Logical Reasoning'],
    ['Odd one out: compare the gap pattern inside each letter group.',
      'Word-based: “How many letters remain at the same position after arranging alphabetically?” — write positions.']),

  // ---------------- Numerical Ability ----------------
  t('simplification', 'numerical', 'Simplification', 'high',
    ['BODMAS', 'Fractions', 'Decimals', 'Percentage-Based Calculations', 'Square/Square Root', 'Cube/Cube Root', 'Basic Mathematical Operations'],
    ['BODMAS: Brackets → Of → Division → Multiplication → Addition → Subtraction.',
      'Learn squares to 30, cubes to 20, fractions 1/2 … 1/20 as percentages.',
      'Use unit-digit checks to eliminate options quickly.']),
  t('approximation', 'numerical', 'Approximation', 'high',
    ['Approximation', 'Rounding decimals', 'Approximate percentages', 'Approximate roots'],
    ['Round each number to the nearest convenient integer before calculating.',
      'Options are usually far apart — estimate, don’t calculate exactly.']),
  t('number-series', 'numerical', 'Number Series', 'high',
    ['Missing Number Series', 'Wrong Number Series', 'Pattern-Based Series', 'Arithmetic Series', 'Mixed Series'],
    ['Check differences first; then second differences; then ratios (×2, ×1.5…).',
      'Look for squares/cubes (n² ± k) and alternating patterns (×a + b).',
      'Wrong number: find the pattern that fits all but one term.']),
  t('quadratic-equations', 'numerical', 'Quadratic Equations', 'medium',
    ['Comparing roots of x and y', 'Factorisation', 'Sign method'],
    ['x² − (a+b)x + ab = 0 has roots a and b. Sign of middle term flips the sign of roots.',
      'Compare every x-root with every y-root; if the relation is not the same for all pairs ⇒ “cannot be established”.',
      'Not listed in the IBPS-provided chapter checklist, but asked in previous RRB OA prelims papers.']),
  t('number-system', 'numerical', 'Number System', 'medium',
    ['Natural/Whole Numbers & Integers', 'Even/Odd & Prime Numbers', 'Factors & Multiples', 'Divisibility Rules', 'LCM & HCF', 'Remainders', 'Unit Digit'],
    ['LCM × HCF = product of two numbers.',
      'Unit digit of powers cycles every 4: find exponent mod 4.',
      'Divisible by 3/9 ⇒ digit sum; by 11 ⇒ alternate-digit difference.']),
  t('percentage', 'numerical', 'Percentage', 'high',
    ['Basic Percentage', 'Percentage Increase/Decrease', 'Successive Percentage', 'Comparison Using Percentage'],
    ['Successive change a% and b% ⇒ a + b + ab/100.',
      'If price rises r%, consumption must fall r/(100 + r) × 100% to keep spend same.',
      'x% of y = y% of x.']),
  t('ratio-proportion', 'numerical', 'Ratio & Proportion', 'high',
    ['Basic Ratio', 'Proportion', 'Direct/Inverse Proportion', 'Ratio-Based Word Problems'],
    ['Combine ratios by equalising the common term: a:b and b:c.',
      'Mean proportional of a and b = √(ab); third proportional = b²/a.']),
  t('average', 'numerical', 'Average', 'high',
    ['Simple Average', 'Weighted Average', 'Average-Based Word Problems'],
    ['Sum = average × count. Track change in sum when someone joins/leaves.',
      'Average of consecutive numbers = (first + last)/2.']),
  t('profit-loss', 'numerical', 'Profit, Loss & Discount', 'high',
    ['Cost Price', 'Selling Price', 'Marked Price', 'Profit/Loss Percentage', 'Discount', 'Successive Discount'],
    ['Profit% is always on CP; discount% is always on MP.',
      'SP = CP × (100 + P%)/100; SP = MP × (100 − D%)/100.',
      'Successive discounts a%, b% ⇒ a + b − ab/100.']),
  t('simple-interest', 'numerical', 'Simple Interest', 'high',
    ['Simple Interest', 'Principal', 'Rate', 'Time', 'Amount'],
    ['SI = P × R × T / 100; Amount = P + SI.',
      'Money doubles in 100/R years at simple interest.']),
  t('compound-interest', 'numerical', 'Compound Interest', 'high',
    ['Compound Interest', 'Difference between SI and CI', 'Half-yearly compounding'],
    ['A = P(1 + R/100)ᵀ.',
      'CI − SI for 2 years = P(R/100)².',
      '2-year effective rate = 2R + R²/100.']),
  t('time-work', 'numerical', 'Time & Work', 'high',
    ['Work Efficiency', 'Individual Work', 'Combined Work', 'Work and Wages', 'Pipes and Cisterns'],
    ['Take total work = LCM of individual days; efficiency = work/day.',
      'Wages are shared in the ratio of work done.',
      'Outlet pipes have negative efficiency.']),
  t('time-distance', 'numerical', 'Time, Speed & Distance', 'high',
    ['Basic Speed/Distance/Time', 'Relative Speed', 'Trains', 'Boats and Streams', 'Basic Race Problems'],
    ['km/h → m/s: × 5/18.',
      'Train crossing a pole: distance = train length; a platform: train + platform length.',
      'Downstream = B + S, upstream = B − S.']),
  t('ages', 'numerical', 'Problems on Ages', 'medium',
    ['Present Age', 'Past Age', 'Future Age', 'Age Ratios'],
    ['The difference between two people’s ages never changes.',
      'Use ratio multipliers: present ages 3x and 5x.']),
  t('mixture-alligation', 'numerical', 'Mixture & Alligation', 'medium',
    ['Basic Mixtures', 'Alligation', 'Replacement Problems'],
    ['Alligation: (dearer − mean) : (mean − cheaper) = quantity of cheaper : dearer.',
      'Replacement: final = initial × (1 − x/total)ⁿ.']),
  t('partnership', 'numerical', 'Partnership', 'medium',
    ['Investment Ratio', 'Time-Based Investment', 'Profit Sharing'],
    ['Profit share ∝ capital × time.',
      'A working partner’s salary is deducted before sharing the remaining profit.']),
  t('data-interpretation', 'numerical', 'Data Interpretation', 'high',
    ['Table DI', 'Bar Graph', 'Line Graph', 'Pie Chart', 'Caselet DI', 'Missing DI', 'Basic Comparison DI'],
    ['Read the units and the heading before any question.',
      'Ratio and percentage questions: simplify fractions before multiplying.',
      'Approximate when options are far apart.']),
  t('mensuration', 'numerical', 'Mensuration', 'low',
    ['Basic Area', 'Perimeter', 'Rectangle', 'Square', 'Triangle', 'Circle', 'Basic Volume'],
    ['Circle: area πr², circumference 2πr (use π = 22/7).',
      'Rectangle: area lb, perimeter 2(l + b). Cuboid volume lbh, cube a³.']),
]

export const topicById = Object.fromEntries(TOPICS.map((x) => [x.id, x]))
export const topicsOf = (subject, topics = TOPICS) => topics.filter((x) => x.subject === subject)
export const topicName = (id) => topicById[id]?.name || id
