// Computer Knowledge question bank. Row: [id, difficulty, stem, correct, [3 wrong], explanation, subtopic]
export default {
  'computer-fundamentals': [
    ['cf1', 'easy', 'Who is known as the father of the computer?', 'Charles Babbage', ['Alan Turing', 'Tim Berners-Lee', 'Bill Gates'], 'Babbage designed the Analytical Engine.', 'History & generations'],
    ['cf2', 'easy', 'Which part of the CPU performs arithmetic and logical operations?', 'ALU', ['Control Unit', 'RAM', 'Cache'], 'Arithmetic Logic Unit.', 'CPU components'],
    ['cf3', 'medium', 'Second-generation computers used:', 'Transistors', ['Vacuum tubes', 'Integrated circuits', 'Microprocessors'], '1st vacuum tubes, 2nd transistors, 3rd ICs, 4th microprocessors.', 'History & generations'],
    ['cf4', 'medium', 'Which generation of computers introduced microprocessors?', 'Fourth', ['Second', 'Third', 'Fifth'], 'Fourth generation = microprocessors (VLSI).', 'History & generations'],
    ['cf5', 'easy', 'How many bits make one byte?', '8', ['4', '16', '1024'], '1 byte = 8 bits; 4 bits = 1 nibble.', 'Number systems'],
    ['cf6', 'hard', 'The base of the hexadecimal number system is:', '16', ['8', '10', '2'], 'Hexadecimal uses 0–9 and A–F.', 'Number systems'],
    ['cf7', 'medium', 'Which unit directs and coordinates all operations of the computer?', 'Control Unit', ['ALU', 'Monitor', 'Hard disk'], 'The Control Unit manages the flow of data and instructions.', 'CPU components'],
    ['cf8', 'hard', 'ENIAC is known as:', 'The first general-purpose electronic computer', ['The first personal computer', 'The first laptop', 'The first mobile phone'], 'ENIAC (1945–46) was the first general-purpose electronic digital computer.', 'History & generations'],
  ],
  'computer-hardware': [
    ['ch1', 'easy', 'Which of the following is an input device?', 'Scanner', ['Monitor', 'Printer', 'Speaker'], 'A scanner sends data into the computer.', 'Input devices'],
    ['ch2', 'easy', 'Which of the following is an output device?', 'Plotter', ['Keyboard', 'Mouse', 'Microphone'], 'A plotter draws output on paper.', 'Output devices'],
    ['ch3', 'medium', 'Banks use which technology to read the special numbers printed on cheques?', 'MICR', ['OMR', 'OCR', 'Barcode reader'], 'Magnetic Ink Character Recognition reads magnetic-ink characters on cheques.', 'Input devices'],
    ['ch4', 'medium', 'Which device can act as both input and output?', 'Touch screen', ['Printer', 'Scanner', 'Keyboard'], 'A touch screen shows output and accepts touch input.', 'Input devices'],
    ['ch5', 'medium', 'OMR is mainly used for:', 'Reading marked answer sheets', ['Reading cheques', 'Printing documents', 'Scanning photographs'], 'Optical Mark Recognition detects filled bubbles.', 'Input devices'],
    ['ch6', 'hard', 'Which of the following is an impact printer?', 'Dot-matrix printer', ['Laser printer', 'Inkjet printer', 'Thermal printer'], 'Dot-matrix printers strike an ink ribbon; laser and inkjet are non-impact.', 'Output devices'],
    ['ch7', 'easy', 'USB stands for:', 'Universal Serial Bus', ['Universal System Board', 'Unified Serial Bus', 'Universal Storage Bank'], 'USB is a standard port for connecting devices.', 'Ports'],
    ['ch8', 'medium', 'Which port carries both high-definition video and audio?', 'HDMI', ['VGA', 'PS/2', 'Serial port'], 'HDMI carries digital audio and video; VGA is video only.', 'Ports'],
  ],
  'computer-memory': [
    ['cm1', 'easy', 'Which memory loses its data when the power is switched off?', 'RAM', ['ROM', 'Hard disk', 'DVD'], 'RAM is volatile.', 'Primary memory (RAM/ROM)'],
    ['cm2', 'easy', 'BIOS is stored in:', 'ROM', ['RAM', 'Cache', 'Registers'], 'BIOS is firmware stored in non-volatile ROM (flash).', 'Primary memory (RAM/ROM)'],
    ['cm3', 'medium', 'Which is the fastest memory in a computer?', 'Registers', ['Cache', 'RAM', 'Hard disk'], 'Registers are inside the CPU and fastest of all.', 'Cache & registers'],
    ['cm4', 'medium', 'Which type of ROM can be erased using ultraviolet light?', 'EPROM', ['PROM', 'EEPROM', 'Mask ROM'], 'EPROM is erased by UV light; EEPROM electrically.', 'Primary memory (RAM/ROM)'],
    ['cm5', 'easy', '1 KB is equal to:', '1024 bytes', ['1000 bytes', '1024 bits', '8 bytes'], 'Memory units go in powers of 2: 1 KB = 2¹⁰ bytes.', 'Units of memory'],
    ['cm6', 'medium', 'Cache memory is placed between:', 'CPU and main memory', ['RAM and hard disk', 'Keyboard and CPU', 'Monitor and CPU'], 'Cache reduces the time the CPU waits for data from RAM.', 'Cache & registers'],
    ['cm7', 'hard', 'Which type of RAM is used for cache memory?', 'SRAM', ['DRAM', 'EPROM', 'Flash'], 'Static RAM is faster and does not need refreshing.', 'Cache & registers'],
    ['cm8', 'medium', 'Which of the following is secondary storage?', 'Hard disk', ['RAM', 'Cache', 'Registers'], 'Secondary storage keeps data permanently outside main memory.', 'Secondary storage'],
  ],
  'software-os': [
    ['so1', 'easy', 'Which of the following is an operating system?', 'Linux', ['MS Word', 'Google Chrome', 'Tally'], 'Linux is an OS; the others are applications.', 'System vs application software'],
    ['so2', 'easy', 'MS Excel is an example of:', 'Application software', ['System software', 'Operating system', 'Compiler'], 'It helps the user do a task (spreadsheets).', 'System vs application software'],
    ['so3', 'medium', 'Which translator converts a whole high-level program into machine code at once?', 'Compiler', ['Interpreter', 'Assembler', 'Loader'], 'An interpreter works line by line; an assembler converts assembly language.', 'Language translators'],
    ['so4', 'medium', 'An assembler converts:', 'Assembly language into machine code', ['High-level language into assembly', 'Machine code into English', 'Text into speech'], 'Assembler = assembly → machine code.', 'Language translators'],
    ['so5', 'medium', 'Restarting a computer that is already on is called:', 'Warm booting', ['Cold booting', 'Shutting down', 'Formatting'], 'Cold boot starts from power-off.', 'Operating system functions'],
    ['so6', 'hard', 'Which of the following is NOT a function of an operating system?', 'Writing business letters', ['Memory management', 'Process management', 'File management'], 'Writing letters is done by application software such as a word processor.', 'Operating system functions'],
    ['so7', 'medium', 'GUI stands for:', 'Graphical User Interface', ['General User Instruction', 'Graphic Unit Interface', 'Global User Internet'], 'A GUI lets users interact through icons and windows.', 'Operating system functions'],
    ['so8', 'hard', 'Antivirus software is generally classified as:', 'Utility software', ['Application software for documents', 'Programming language', 'Hardware'], 'Utility programs (antivirus, disk cleanup) maintain the computer.', 'Utility software'],
  ],
  'ms-office': [
    ['mo1', 'easy', 'What is the default file extension of a document created in MS Word 2007 or later?', '.docx', ['.xlsx', '.pptx', '.txt'], '.xlsx — Excel; .pptx — PowerPoint.', 'File extensions'],
    ['mo2', 'easy', 'In MS Excel, every formula must begin with:', '=', ['+', '#', '@'], 'Formulas start with an equals sign.', 'MS Excel'],
    ['mo3', 'medium', 'In MS Excel, the cell in column C and row 5 is written as:', 'C5', ['5C', 'C:5', 'R5C'], 'Cell address = column letter + row number.', 'MS Excel'],
    ['mo4', 'medium', 'Which shortcut centres the selected text in MS Word?', 'Ctrl + E', ['Ctrl + C', 'Ctrl + T', 'Ctrl + M'], 'Ctrl+C copies; Ctrl+E centres.', 'MS Word'],
    ['mo5', 'medium', 'Which key starts a PowerPoint slide show from the first slide?', 'F5', ['F7', 'F2', 'F12'], 'Shift+F5 starts from the current slide.', 'MS PowerPoint'],
    ['mo6', 'hard', 'In MS Excel, $A$1 is an example of:', 'An absolute reference', ['A relative reference', 'A mixed reference', 'A range name'], 'Dollar signs lock both column and row when copied.', 'MS Excel'],
    ['mo7', 'medium', 'Which key checks spelling and grammar in MS Word?', 'F7', ['F5', 'F1', 'F4'], 'F7 opens the spelling and grammar check.', 'MS Word'],
    ['mo8', 'hard', 'Which Excel function counts the cells that contain numbers?', 'COUNT', ['SUM', 'AVERAGE', 'MAX'], 'COUNT counts numeric cells; COUNTA counts non-empty cells.', 'MS Excel'],
  ],
  'internet-networking': [
    ['in1', 'easy', 'Which network covers the largest area?', 'WAN', ['LAN', 'MAN', 'PAN'], 'PAN < LAN < MAN < WAN.', 'Types of networks'],
    ['in2', 'easy', 'Which protocol is used to send email?', 'SMTP', ['FTP', 'POP3', 'HTTP'], 'SMTP sends mail; POP3/IMAP receive it.', 'Protocols'],
    ['in3', 'medium', 'DNS is used to:', 'Convert domain names into IP addresses', ['Send emails', 'Encrypt files', 'Store web pages'], 'Domain Name System translates names like example.com into IP addresses.', 'Internet terms'],
    ['in4', 'medium', 'Which protocol is used for secure websites (such as net banking)?', 'HTTPS', ['HTTP', 'FTP', 'SMTP'], 'HTTPS encrypts data between the browser and the website.', 'Protocols'],
    ['in5', 'medium', 'Who invented the World Wide Web?', 'Tim Berners-Lee', ['Charles Babbage', 'Vint Cerf', 'Steve Jobs'], 'Tim Berners-Lee proposed the WWW in 1989.', 'Internet terms'],
    ['in6', 'hard', 'How many bits are there in an IPv4 address?', '32', ['64', '128', '16'], 'IPv4 is 32-bit; IPv6 is 128-bit.', 'Internet terms'],
    ['in7', 'medium', 'In email, the recipients in which field are hidden from other recipients?', 'BCC', ['CC', 'To', 'Subject'], 'Blind Carbon Copy recipients are not visible to others.', 'Email'],
    ['in8', 'medium', 'A device that converts digital signals to analog and back is a:', 'Modem', ['Router', 'Switch', 'Hub'], 'MODEM = MOdulator–DEModulator.', 'Types of networks'],
    ['in9', 'hard', 'In which topology are all devices connected to a central device?', 'Star', ['Bus', 'Ring', 'Mesh'], 'Star topology uses a central hub or switch.', 'Types of networks'],
  ],
  'computer-security': [
    ['cs1', 'easy', 'A fake email that tries to steal your bank password is an example of:', 'Phishing', ['Spamming', 'Hacking hardware', 'Formatting'], 'Phishing uses fake messages or websites to steal details.', 'Phishing & social engineering'],
    ['cs2', 'medium', 'Fraud carried out through phone calls to steal banking details is called:', 'Vishing', ['Smishing', 'Phishing', 'Spoofing'], 'Vishing = voice phishing; smishing = SMS phishing.', 'Phishing & social engineering'],
    ['cs3', 'medium', 'Malware that spreads across networks on its own, without a host file, is a:', 'Worm', ['Virus', 'Trojan', 'Cookie'], 'A virus needs a host file; a worm self-replicates.', 'Malware'],
    ['cs4', 'medium', 'Malware that locks your files and demands payment is called:', 'Ransomware', ['Spyware', 'Adware', 'Firmware'], 'Ransomware encrypts data and asks for a ransom.', 'Malware'],
    ['cs5', 'easy', 'Which of the following should a bank customer NEVER share?', 'OTP', ['Account holder name', 'Branch name', 'IFSC code'], 'Banks never ask for OTP, PIN, CVV or passwords.', 'Safe banking practices'],
    ['cs6', 'medium', 'A program disguised as useful software but secretly harmful is a:', 'Trojan horse', ['Worm', 'Firewall', 'Antivirus'], 'Trojans trick users into installing them.', 'Malware'],
    ['cs7', 'hard', 'A firewall is mainly used to:', 'Filter incoming and outgoing network traffic', ['Remove viruses from files', 'Speed up the internet', 'Back up data'], 'Antivirus removes malware; a firewall controls network traffic.', 'Firewalls & antivirus'],
    ['cs8', 'hard', 'Using a password and an OTP together is an example of:', 'Two-factor authentication', ['Encryption', 'Phishing', 'Single sign-on'], 'Two different factors: something you know and something you have.', 'Firewalls & antivirus'],
  ],
  'keyboard-shortcuts': [
    ['ks1', 'easy', 'Which shortcut is used to undo the last action?', 'Ctrl + Z', ['Ctrl + Y', 'Ctrl + U', 'Ctrl + X'], 'Ctrl+Y redoes; Ctrl+X cuts.', 'Windows shortcuts'],
    ['ks2', 'easy', 'Which shortcut selects all items in a document?', 'Ctrl + A', ['Ctrl + S', 'Ctrl + E', 'Ctrl + L'], 'A for All.', 'Windows shortcuts'],
    ['ks3', 'medium', 'Which shortcut closes the active window?', 'Alt + F4', ['Ctrl + F4', 'Alt + Tab', 'Ctrl + W'], 'Alt+F4 closes the active window/program.', 'Windows shortcuts'],
    ['ks4', 'medium', 'Which shortcut locks a Windows computer?', 'Windows + L', ['Windows + D', 'Ctrl + L', 'Alt + L'], 'Win+D shows the desktop.', 'Windows shortcuts'],
    ['ks5', 'medium', 'Which shortcut opens Task Manager directly?', 'Ctrl + Shift + Esc', ['Ctrl + Alt + T', 'Alt + Esc', 'Shift + Esc'], 'Ctrl+Shift+Esc opens Task Manager.', 'Windows shortcuts'],
    ['ks6', 'easy', 'Which key renames a selected file in Windows?', 'F2', ['F1', 'F5', 'F12'], 'F2 = rename; F5 = refresh.', 'Windows shortcuts'],
    ['ks7', 'hard', 'In MS Office, which key opens the “Save As” dialog?', 'F12', ['F2', 'F7', 'F10'], 'F12 = Save As.', 'MS Office shortcuts'],
    ['ks8', 'medium', 'PDF stands for:', 'Portable Document Format', ['Printed Document File', 'Public Data Format', 'Personal Document File'], 'PDF keeps a document’s layout the same on every device.', 'Common abbreviations'],
  ],
  'dbms-basics': [
    ['db1', 'easy', 'In a database table, a row is also called a:', 'Record', ['Field', 'Key', 'Column'], 'Row = record/tuple; column = field/attribute.', 'Tables, rows & columns'],
    ['db2', 'medium', 'A key that uniquely identifies each row of a table is the:', 'Primary key', ['Foreign key', 'Duplicate key', 'Secondary index'], 'A primary key is unique and cannot be empty.', 'Keys'],
    ['db3', 'medium', 'A key that links one table to the primary key of another table is a:', 'Foreign key', ['Primary key', 'Candidate key', 'Super key'], 'Foreign keys create relationships between tables.', 'Keys'],
    ['db4', 'medium', 'Which SQL command is used to retrieve data?', 'SELECT', ['INSERT', 'DROP', 'ALTER'], 'SELECT reads data from a table.', 'SQL basics'],
    ['db5', 'hard', 'Which of the following is a DDL command?', 'CREATE', ['SELECT', 'UPDATE', 'INSERT'], 'DDL (structure): CREATE, ALTER, DROP. DML (data): SELECT, INSERT, UPDATE, DELETE.', 'SQL basics'],
    ['db6', 'hard', 'Which command removes an entire table, including its structure?', 'DROP', ['DELETE', 'UPDATE', 'SELECT'], 'DELETE removes rows; DROP removes the whole table.', 'SQL basics'],
  ],
}
