// General Awareness question bank — stable, verified facts only (see src/lib/guides/ga.js).
// Row: [id, difficulty, stem, correct, [3 wrong], explanation, subtopic]
export default {
  'banking-awareness': [
    ['ba1', 'easy', 'When was the Reserve Bank of India established?', '1 April 1935', ['1 January 1949', '15 August 1947', '19 July 1969'], 'The RBI began operations on 1 April 1935 under the RBI Act, 1934. It was nationalised on 1 January 1949.', 'RBI & its functions'],
    ['ba2', 'easy', 'Where is the headquarters of the Reserve Bank of India?', 'Mumbai', ['New Delhi', 'Kolkata', 'Chennai'], 'The RBI’s central office is in Mumbai (it was originally in Kolkata).', 'RBI & its functions'],
    ['ba3', 'easy', 'Regional Rural Banks were first set up on:', '2 October 1975', ['12 July 1982', '1 July 1955', '2 April 1990'], 'RRBs started on 2 October 1975; they are governed by the RRB Act, 1976.', 'Regional Rural Banks'],
    ['ba4', 'medium', 'What share of an RRB is held by its sponsor bank?', '35%', ['50%', '15%', '25%'], 'Central Government 50%, sponsor bank 35%, State Government 15%.', 'Regional Rural Banks'],
    ['ba5', 'medium', 'What share of an RRB is held by the Central Government?', '50%', ['35%', '15%', '51%'], 'Central Government 50%, sponsor bank 35%, State Government 15%.', 'Regional Rural Banks'],
    ['ba6', 'medium', 'Regional Rural Banks are governed by which Act?', 'Regional Rural Banks Act, 1976', ['Banking Regulation Act, 1949', 'NABARD Act, 1981', 'RBI Act, 1934'], 'The RRB Act, 1976 provides for incorporation, regulation and winding-up of RRBs.', 'Regional Rural Banks'],
    ['ba7', 'easy', 'NABARD was established on:', '12 July 1982', ['1 April 1935', '2 April 1990', '2 October 1975'], 'NABARD took over the RBI’s agricultural credit functions on 12 July 1982.', 'NABARD & development banks'],
    ['ba8', 'medium', 'Where is the headquarters of SIDBI?', 'Lucknow', ['Mumbai', 'New Delhi', 'Hyderabad'], 'SIDBI was set up on 2 April 1990 with its head office in Lucknow.', 'NABARD & development banks'],
    ['ba9', 'medium', 'On 19 July 1969, how many banks were nationalised?', '14', ['6', '20', '12'], '14 major banks were nationalised in 1969 and 6 more in 1980.', 'Types of banks'],
    ['ba10', 'easy', 'What is the minimum amount for an RTGS transfer?', '₹2 lakh', ['₹1 lakh', '₹50,000', 'No minimum'], 'RTGS is meant for large-value transfers; its minimum is ₹2 lakh. NEFT has no minimum.', 'Payment systems'],
    ['ba11', 'medium', 'Which organisation operates UPI?', 'National Payments Corporation of India (NPCI)', ['Reserve Bank of India', 'State Bank of India', 'SEBI'], 'NPCI (incorporated 2008) runs UPI, IMPS and RuPay.', 'Payment systems'],
    ['ba12', 'hard', 'How many characters does an IFSC code have?', '11', ['9', '10', '12'], 'IFSC = 4-letter bank code + “0” + 6-character branch code = 11 characters. (MICR codes have 9 digits.)', 'Payment systems'],
    ['ba13', 'hard', 'The first Regional Rural Bank, Prathama Bank, was set up at:', 'Moradabad', ['Lucknow', 'Patna', 'Jaipur'], 'Prathama Bank was set up at Moradabad (Uttar Pradesh) on 2 October 1975.', 'Regional Rural Banks'],
  ],
  'financial-awareness': [
    ['fa1', 'easy', 'The rate at which the RBI lends short-term money to banks against securities is called:', 'Repo rate', ['Reverse repo rate', 'Bank rate', 'Cash Reserve Ratio'], 'Repo = RBI lends to banks; reverse repo = RBI borrows from banks.', 'Monetary policy tools'],
    ['fa2', 'easy', 'CRR stands for:', 'Cash Reserve Ratio', ['Credit Reserve Rate', 'Current Reserve Ratio', 'Capital Reserve Ratio'], 'CRR is the share of deposits banks must keep as cash with the RBI.', 'Reserve ratios'],
    ['fa3', 'medium', 'The share of deposits that banks must maintain themselves in cash, gold or approved securities is called:', 'SLR', ['CRR', 'Repo rate', 'MSF'], 'Statutory Liquidity Ratio is maintained by the banks themselves; CRR is kept with the RBI.', 'Reserve ratios'],
    ['fa4', 'medium', 'A loan becomes a Non-Performing Asset when interest or principal is overdue for more than:', '90 days', ['30 days', '60 days', '180 days'], 'As per RBI norms, the threshold is more than 90 days.', 'Monetary policy tools'],
    ['fa5', 'medium', 'If the RBI raises the CRR, the money available with banks for lending will:', 'Decrease', ['Increase', 'Stay the same', 'Double'], 'Banks must lock more cash with the RBI, so less is available to lend.', 'Monetary policy tools'],
    ['fa6', 'easy', 'Which body regulates the securities market in India?', 'SEBI', ['IRDAI', 'PFRDA', 'NABARD'], 'SEBI (1988, statutory from 1992) regulates the securities market.', 'Money & capital markets'],
    ['fa7', 'medium', 'Where is the headquarters of IRDAI?', 'Hyderabad', ['Mumbai', 'New Delhi', 'Chennai'], 'The Insurance Regulatory and Development Authority of India is based in Hyderabad.', 'Abbreviations'],
    ['fa8', 'medium', 'CASA deposits refer to:', 'Current Account and Savings Account deposits', ['Cash and Savings Assets', 'Credit Account and Savings Advances', 'Capital Asset Savings Account'], 'A high CASA ratio means cheaper funds for a bank.', 'Abbreviations'],
    ['fa9', 'hard', 'The Consumer Price Index (CPI) in India is released by:', 'National Statistics Office (MoSPI)', ['Reserve Bank of India', 'NITI Aayog', 'SEBI'], 'CPI is released by the NSO under MoSPI; WPI by the Office of the Economic Adviser, DPIIT.', 'Inflation & GDP basics'],
    ['fa10', 'hard', 'Which body regulates the National Pension System (NPS)?', 'PFRDA', ['SEBI', 'IRDAI', 'RBI'], 'The Pension Fund Regulatory and Development Authority (2003) regulates NPS.', 'Abbreviations'],
  ],
  'government-schemes': [
    ['gs1', 'easy', 'Pradhan Mantri Jan Dhan Yojana was launched in:', '2014', ['2015', '2016', '2019'], 'Announced on 15 August 2014 and launched on 28 August 2014.', 'Financial inclusion'],
    ['gs2', 'medium', 'What is the life cover under PMJJBY?', '₹2 lakh', ['₹1 lakh', '₹5 lakh', '₹50,000'], 'PMJJBY gives ₹2 lakh life cover for a premium of ₹436 a year.', 'Insurance & pension'],
    ['gs3', 'medium', 'What is the annual premium for PMSBY?', '₹20', ['₹12', '₹330', '₹436'], 'PMSBY accident cover of ₹2 lakh costs ₹20 a year (revised from ₹12 in 2022).', 'Insurance & pension'],
    ['gs4', 'medium', 'Atal Pension Yojana is open to people aged:', '18 to 40 years', ['18 to 50 years', '18 to 70 years', '21 to 60 years'], 'APY joining age is 18–40; pension of ₹1,000–5,000 a month from age 60.', 'Insurance & pension'],
    ['gs5', 'easy', 'Under PM-KISAN, eligible farmers receive how much per year?', '₹6,000', ['₹12,000', '₹2,000', '₹10,000'], '₹6,000 a year in three instalments of ₹2,000 (launched 24 February 2019).', 'Agriculture'],
    ['gs6', 'medium', 'Under PM MUDRA Yojana, loans up to ₹50,000 fall in which category?', 'Shishu', ['Kishore', 'Tarun', 'Tarun Plus'], 'Shishu ≤ ₹50,000; Kishore ₹50,000–5 lakh; Tarun ₹5–10 lakh; Tarun Plus ₹10–20 lakh.', 'Entrepreneurship & credit'],
    ['gs7', 'hard', 'Stand-Up India provides loans between:', '₹10 lakh and ₹1 crore', ['₹50,000 and ₹10 lakh', '₹1 lakh and ₹10 lakh', '₹1 crore and ₹5 crore'], 'For greenfield enterprises by SC/ST and women entrepreneurs (launched 5 April 2016).', 'Entrepreneurship & credit'],
    ['gs8', 'medium', 'Which scheme provides crop insurance to farmers?', 'Pradhan Mantri Fasal Bima Yojana', ['PM-KISAN', 'Stand-Up India', 'Atal Pension Yojana'], 'PMFBY (2016) is the crop insurance scheme.', 'Agriculture'],
    ['gs9', 'hard', 'The Kisan Credit Card scheme was introduced in:', '1998', ['2004', '1991', '2014'], 'KCC was introduced in August 1998 on the model prepared by NABARD (R.V. Gupta Committee).', 'Agriculture'],
    ['gs10', 'hard', 'PMJJBY, PMSBY and Atal Pension Yojana were launched on:', '9 May 2015', ['28 August 2014', '8 April 2015', '5 April 2016'], 'The three Jan Suraksha schemes were launched together on 9 May 2015.', 'Insurance & pension'],
  ],
  'static-gk': [
    ['sg1', 'easy', 'Where is the headquarters of the World Trade Organization?', 'Geneva', ['New York', 'Paris', 'Washington, D.C.'], 'WTO, WHO and ILO are all in Geneva.', 'International organisations'],
    ['sg2', 'easy', 'Where is the headquarters of the IMF?', 'Washington, D.C.', ['Geneva', 'New York', 'London'], 'The IMF and the World Bank are both in Washington, D.C.', 'International organisations'],
    ['sg3', 'medium', 'The Asian Development Bank is headquartered in:', 'Manila', ['Beijing', 'Tokyo', 'Shanghai'], 'ADB — Manila; AIIB — Beijing; New Development Bank — Shanghai.', 'International organisations'],
    ['sg4', 'easy', 'What is the currency of Bangladesh?', 'Taka', ['Rupee', 'Ngultrum', 'Kyat'], 'Bhutan — Ngultrum; Myanmar — Kyat.', 'Currencies & capitals'],
    ['sg5', 'medium', 'What is the currency of Bhutan?', 'Ngultrum', ['Taka', 'Rupiah', 'Kyat'], 'Bhutan’s currency is the Ngultrum.', 'Currencies & capitals'],
    ['sg6', 'medium', 'Which Article of the Indian Constitution deals with the Finance Commission?', 'Article 280', ['Article 21', 'Article 148', 'Article 112'], 'Art. 280 — Finance Commission; Art. 148 — CAG; Art. 112 — Budget.', 'Constitution basics'],
    ['sg7', 'medium', 'The Annual Financial Statement (Union Budget) is mentioned in which Article?', 'Article 112', ['Article 280', 'Article 32', 'Article 360'], 'Article 112 requires the Annual Financial Statement to be laid before Parliament.', 'Constitution basics'],
    ['sg8', 'easy', 'World Environment Day is observed on:', '5 June', ['22 April', '5 May', '7 April'], '5 June is World Environment Day; 7 April is World Health Day.', 'Important days'],
    ['sg9', 'medium', 'National Farmers’ Day (Kisan Diwas) in India is observed on:', '23 December', ['26 November', '15 January', '2 October'], 'It marks the birth anniversary of former Prime Minister Chaudhary Charan Singh.', 'Important days'],
    ['sg10', 'hard', 'The Bank for International Settlements is headquartered in:', 'Basel', ['Geneva', 'Brussels', 'Frankfurt'], 'The BIS is based in Basel, Switzerland.', 'International organisations'],
  ],
  'agriculture-rural': [
    ['ag1', 'easy', 'Which of the following is a Rabi crop?', 'Wheat', ['Rice', 'Cotton', 'Maize'], 'Rabi crops (wheat, mustard, gram) are sown in winter.', 'Crop seasons'],
    ['ag2', 'easy', 'Kharif crops are sown at the beginning of the:', 'Monsoon season', ['Winter season', 'Summer season', 'Spring season'], 'Kharif crops such as rice and maize are sown in June–July.', 'Crop seasons'],
    ['ag3', 'medium', 'The White Revolution in India is associated with:', 'Milk production', ['Food grains', 'Fisheries', 'Oilseeds'], 'Operation Flood, led by Dr Verghese Kurien.', 'Agricultural revolutions'],
    ['ag4', 'medium', 'Who is known as the father of the Green Revolution in India?', 'M.S. Swaminathan', ['Verghese Kurien', 'C. Rangarajan', 'Raghuram Rajan'], 'The Green Revolution increased food-grain production.', 'Agricultural revolutions'],
    ['ag5', 'medium', 'What is the priority sector lending target for Regional Rural Banks?', '75% of advances', ['40% of advances', '18% of advances', '60% of advances'], 'RRBs: 75%; domestic scheduled commercial banks: 40%.', 'Rural credit'],
    ['ag6', 'hard', 'Which institution refinances Regional Rural Banks for agricultural lending?', 'NABARD', ['SIDBI', 'EXIM Bank', 'SEBI'], 'NABARD is the apex body for rural credit and refinances RRBs and cooperatives.', 'Rural credit'],
    ['ag7', 'medium', 'Watermelon and cucumber are typical crops of which season?', 'Zaid', ['Kharif', 'Rabi', 'Winter'], 'Zaid crops grow in the short summer season between Rabi and Kharif.', 'Crop seasons'],
    ['ag8', 'hard', 'The Blue Revolution is related to:', 'Fisheries', ['Milk', 'Oilseeds', 'Food grains'], 'Blue Revolution = fish production.', 'Agricultural revolutions'],
  ],
}
