// Numerical Ability topic guides. Every formula here is checked numerically in src/test/guides.test.js.
// Shape: { concept, shortcuts: [[title, detail]], formulas: [..], quick: [..steps], traps: [..] }

export default {
  simplification: {
    concept: 'Simplify an expression in the correct order (BODMAS) and pick the exact value. Speed comes from mental arithmetic and from eliminating options without full calculation.',
    shortcuts: [
      ['Unit-digit check', 'Work out only the last digit of the answer first — often only one option matches.'],
      ['Digit-sum (casting out 9s)', 'For +, − and ×, the digit sum of the answer (reduced to one digit) equals the same operation on the digit sums of the numbers. Use it to verify an option quickly.'],
      ['Multiply by 5, 25, 125', '×5 = ×10 ÷ 2; ×25 = ×100 ÷ 4; ×125 = ×1000 ÷ 8.'],
      ['Squares ending in 5', '(n5)² = n × (n+1) followed by 25. Example: 65² → 6 × 7 = 42 → 4225.'],
      ['Squares near 50', '(50 + a)² = 2500 + 100a + a². Example: 53² = 2500 + 300 + 9 = 2809.'],
      ['×11 for two-digit numbers', 'For ab × 11 write a, (a + b), b and carry if needed. 47 × 11 → 4 | 11 | 7 → 517.'],
      ['Percent ↔ fraction', '12.5% = 1/8, 16.67% = 1/6, 33.33% = 1/3, 37.5% = 3/8, 62.5% = 5/8, 87.5% = 7/8.'],
    ],
    formulas: ['(a + b)² = a² + 2ab + b²', '(a − b)² = a² − 2ab + b²', 'a² − b² = (a + b)(a − b)', '(a + b)³ = a³ + b³ + 3ab(a + b)'],
    quick: ['Solve brackets and “of” first.', 'Convert percentages to fractions where it simplifies.', 'Before calculating fully, check unit digits of the options.', 'For “? ” in the middle, move every known term to the other side first.'],
    traps: ['“of” is done before division: 1/2 of 40 ÷ 4 = 20 ÷ 4 = 5.', 'Subtraction is not associative: 50 − 20 − 10 = 20, not 40.'],
  },
  approximation: {
    concept: 'Round every number to a convenient value, calculate roughly and choose the nearest option. Exact calculation wastes time.',
    shortcuts: [
      ['Round to friendly numbers', '24.98% → 25%, 399.87 → 400, 12.03 × 7.96 → 12 × 8.'],
      ['Nearest perfect square/cube', '√730 ≈ 27 (27² = 729); ∛215 ≈ 6 (6³ = 216).'],
      ['Balance the rounding', 'If you round one number up, round a similar-sized one down to keep the error small.'],
      ['Read the option gap first', 'If options differ by 50+, rough mental work is enough.'],
    ],
    formulas: ['x% of y = y% of x', '√(a × b) = √a × √b'],
    quick: ['Glance at the options to see how far apart they are.', 'Round each number.', 'Calculate mentally and pick the closest option.'],
    traps: ['Do not round both numbers of a large product in the same direction when options are close.'],
  },
  'number-series': {
    concept: 'Find the rule that generates the series and use it to get the missing term or to spot the one wrong term.',
    shortcuts: [
      ['Growth speed tells the operation', 'Slow, steady growth → addition/subtraction. Fast growth (doubling or more) → multiplication. Up-and-down → alternate operations.'],
      ['Difference ladder', 'Write first differences; if not constant, write second differences. Constant second difference means the first differences form an AP.'],
      ['Squares & cubes nearby', 'Check if terms are n² ± k or n³ ± k, or if differences are consecutive squares/cubes.'],
      ['×n + k pattern', 'Try “previous × 2 + 1”, “× 3 − 1”, or multipliers that increase (×1, ×2, ×3 …) or step by 0.5 (×0.5, ×1, ×1.5 …).'],
      ['Alternate series', 'If nothing fits, split odd and even positions into two separate series.'],
      ['Wrong-number series', 'Find the pattern from the terms that fit; the one term that breaks it is the answer — usually off by a small amount.'],
    ],
    formulas: ['Squares 1–30 and cubes 1–20 must be memorised.', 'Primes up to 100: 2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97.'],
    quick: ['Look at the size of growth.', 'Take differences (twice if needed).', 'Test multiplication patterns.', 'Try alternate positions.'],
    traps: ['A series can have the same differences pattern starting from a different square — check every step, not just the first two.'],
  },
  'quadratic-equations': {
    concept: 'Solve two quadratic equations (in x and in y), then compare every root of x with every root of y.',
    shortcuts: [
      ['Sign rule (x² + bx + c = 0)', 'b +, c + → both roots negative. b −, c + → both roots positive. c − → one positive, one negative root.'],
      ['Factor pair method', 'For ax² + bx + c, find two numbers whose product is a × c and sum is b. The roots are those numbers divided by a, with signs reversed.'],
      ['Sum & product check', 'Sum of roots = −b/a, product = c/a. Use it to verify your roots in seconds.'],
      ['Comparison grid', 'Write x-roots in one row and y-roots in one column; if every pair gives the same sign of x − y, the relation is fixed.'],
    ],
    formulas: ['Roots = [−b ± √(b² − 4ac)] / 2a', 'Sum of roots = −b/a; product = c/a', 'x² = k ⇒ x = ±√k (equal-magnitude roots of both signs)'],
    quick: ['Get both roots of I.', 'Get both roots of II.', 'Compare all four pairs.', 'Mixed results → “relationship cannot be established”.'],
    traps: ['x² = 16 gives x = +4 AND −4 — students often take only +4.', 'If one pair is equal and others are “>”, the answer is “x ≥ y”, not “x > y”.'],
  },
  'number-system': {
    concept: 'Properties of numbers: divisibility, factors, LCM/HCF, remainders and unit digits.',
    shortcuts: [
      ['Divisibility tests', '2: last digit even; 3/9: digit sum divisible by 3/9; 4: last two digits; 8: last three digits; 5: ends in 0/5; 11: (sum of odd-place digits − sum of even-place digits) is 0 or a multiple of 11.'],
      ['Unit-digit cycles', 'Digits 0, 1, 5, 6 repeat themselves. 4 and 9 cycle every 2. 2, 3, 7, 8 cycle every 4 — divide the power by 4 and use the remainder (remainder 0 → 4th term).'],
      ['Remainder of a product', '(a × b) mod n = [(a mod n) × (b mod n)] mod n — reduce first, multiply small numbers.'],
      ['LCM/HCF of fractions', 'HCF = HCF(numerators)/LCM(denominators); LCM = LCM(numerators)/HCF(denominators).'],
      ['Number of factors', 'If N = pᵃ × qᵇ × rᶜ, the number of factors = (a + 1)(b + 1)(c + 1).'],
    ],
    formulas: ['LCM × HCF = product of the two numbers', '1 + 2 + … + n = n(n + 1)/2', '1² + 2² + … + n² = n(n + 1)(2n + 1)/6', 'Sum of first n odd numbers = n²'],
    quick: ['Identify which property is asked (factor, remainder, unit digit).', 'Reduce big numbers using the rules above before calculating.'],
    traps: ['LCM × HCF = product works for TWO numbers only.'],
  },
  percentage: {
    concept: 'A percentage is a fraction with denominator 100. Most questions are about change, comparison or successive change.',
    shortcuts: [
      ['Fraction table', '1/2 = 50%, 1/3 = 33.33%, 1/4 = 25%, 1/5 = 20%, 1/6 = 16.67%, 1/7 ≈ 14.29%, 1/8 = 12.5%, 1/9 ≈ 11.11%, 1/11 ≈ 9.09%, 1/12 = 8.33%, 1/16 = 6.25%.'],
      ['Split the percentage', '35% of 840 = 25% (210) + 10% (84) = 294.'],
      ['Successive change', 'Two changes a% and b% give a net change of a + b + ab/100 (use − for decreases).'],
      ['More than → less than', 'If A is r% more than B, B is r/(100 + r) × 100% less than A. If A is r% less than B, B is r/(100 − r) × 100% more than A.'],
      ['Price up, keep spending same', 'If price rises r%, consumption must fall by r/(100 + r) × 100%.'],
      ['Swap trick', 'x% of y = y% of x: 16% of 25 = 25% of 16 = 4.'],
    ],
    formulas: ['% change = (new − old)/old × 100', 'Value after n years at r% growth = P(1 + r/100)ⁿ', 'Value after r% increase = original × (100 + r)/100'],
    quick: ['Convert % into a fraction if it is in the table.', 'For successive changes, use the a + b + ab/100 rule.', 'For “by what % is B less”, the base is always the value you compare WITH.'],
    traps: ['A 20% rise followed by a 20% fall is a 4% net LOSS, not zero.'],
  },
  'ratio-proportion': {
    concept: 'A ratio compares two quantities of the same kind; a proportion says two ratios are equal.',
    shortcuts: [
      ['Combine ratios', 'For A:B = a:b and B:C = c:d, make B equal: A:B:C = ac : bc : bd.'],
      ['Share of a total', 'Share = total × (its part) / (sum of parts).'],
      ['Add the same number to both', 'If (a + k)/(b + k) is given, cross-multiply with the unknown multiplier x: (ax + k)d = (bx + k)c.'],
      ['Third and fourth proportional', 'a : b :: b : x ⇒ x = b²/a. a : b :: c : x ⇒ x = bc/a. Mean proportional of a and b = √(ab).'],
    ],
    formulas: ['a : b = c : d ⇔ ad = bc', 'Direct proportion: x/y constant; inverse proportion: x × y constant'],
    quick: ['Write each quantity as (ratio part) × x.', 'Form one equation in x from the condition.', 'Answer what is asked (often one person’s share, not x).'],
    traps: ['Ratios must be in the same units before comparing.'],
  },
  average: {
    concept: 'Average = sum of observations ÷ number of observations. Most questions track how the SUM changes.',
    shortcuts: [
      ['Work with the sum', 'Sum = average × count. When someone joins or leaves, compare sums.'],
      ['Replacement', 'If one person is replaced and the average of n people rises by d, the new person is n × d more than the person replaced.'],
      ['Consecutive numbers', 'The average of consecutive (or equally spaced) numbers = middle term = (first + last)/2.'],
      ['Deviation method', 'Assume a convenient average, average the deviations, and add to the assumed value.'],
    ],
    formulas: ['Average of first n natural numbers = (n + 1)/2', 'Average of first n odd numbers = n', 'Average of first n even numbers = n + 1', 'Weighted average = (n₁a₁ + n₂a₂)/(n₁ + n₂)'],
    quick: ['Convert every average into a sum.', 'Find the difference of sums.', 'That difference is usually the answer.'],
    traps: ['A combined average is not the simple average of the two averages unless the group sizes are equal.'],
  },
  'profit-loss': {
    concept: 'Profit/loss is calculated on Cost Price (CP); discount is calculated on Marked Price (MP).',
    shortcuts: [
      ['Multiplier method', 'SP = CP × (100 + P%)/100; SP = MP × (100 − D%)/100.'],
      ['MP to CP ratio', 'MP/CP = (100 + P%)/(100 − D%).'],
      ['Same SP, x% profit and x% loss', 'Selling two items at the same price, one at x% profit and one at x% loss, always gives a net loss of x²/100 %.'],
      ['Successive discounts', 'Discounts a% and b% equal a single discount of a + b − ab/100 %.'],
      ['Buy x get y free', 'Effective discount = y/(x + y) × 100%.'],
      ['False weight', 'Profit% = (true weight − false weight)/false weight × 100.'],
    ],
    formulas: ['Profit% = (SP − CP)/CP × 100', 'Discount% = (MP − SP)/MP × 100'],
    quick: ['Identify CP, SP, MP in the question.', 'Use multipliers instead of separate profit amounts.', 'Take CP = 100 when no amount is given.'],
    traps: ['Profit% is on CP, never on SP (unless the question says so).'],
  },
  'simple-interest': {
    concept: 'Simple interest is calculated only on the original principal, so it is the same every year.',
    shortcuts: [
      ['Doubling time', 'A sum doubles in 100/R years at R% simple interest.'],
      ['n times', 'A sum becomes n times in (n − 1) × 100/R years.'],
      ['Yearly interest is constant', 'Interest for 1 year = P × R/100; for T years just multiply by T.'],
    ],
    formulas: ['SI = P × R × T / 100', 'Amount = P + SI = P(1 + RT/100)', 'R = SI × 100/(P × T)', 'T = SI × 100/(P × R)'],
    quick: ['List P, R, T and the unknown.', 'Use the matching rearranged formula.'],
    traps: ['Convert months to years (6 months = 1/2 year).'],
  },
  'compound-interest': {
    concept: 'Compound interest adds each period’s interest to the principal, so interest also earns interest.',
    shortcuts: [
      ['CI − SI for 2 years', 'Difference = P(R/100)².'],
      ['CI − SI for 3 years', 'Difference = P(R/100)²(3 + R/100).'],
      ['Effective 2-year rate', '2R + R²/100 %. At 10%: 21%; at 20%: 44%.'],
      ['Half-yearly / quarterly', 'Half-yearly: rate R/2, periods 2T. Quarterly: rate R/4, periods 4T.'],
      ['Ready multipliers', '10% → 1.1, 1.21, 1.331; 20% → 1.2, 1.44, 1.728; 5% → 1.05, 1.1025.'],
    ],
    formulas: ['A = P(1 + R/100)ᵀ', 'CI = A − P'],
    quick: ['Use ready multipliers for common rates.', 'For CI − SI questions, use the difference formula directly.'],
    traps: ['“Rule of 72” (doubling time ≈ 72/R years) is only an approximation — use it to estimate, not when options are close.'],
  },
  'time-work': {
    concept: 'Work = efficiency × time. Treat the total work as a number of units to avoid fractions.',
    shortcuts: [
      ['LCM unit method', 'Total work = LCM of individual times. Each person’s efficiency = total ÷ their days.'],
      ['Two people together', 'If A takes a days and B takes b days, together they take ab/(a + b) days.'],
      ['Efficiency ratio', 'If A is k times as efficient as B, A takes 1/k of B’s time.'],
      ['Wages', 'Wages are shared in the ratio of work done (efficiency × days worked).'],
      ['Pipes', 'Filling pipes have positive efficiency, emptying pipes negative. Net = sum.'],
    ],
    formulas: ['M₁D₁H₁/W₁ = M₂D₂H₂/W₂ (men × days × hours per work)', 'Time = work/efficiency'],
    quick: ['Take total work = LCM.', 'Find each efficiency in units/day.', 'Add/subtract efficiencies for people working together.'],
    traps: ['Do not add days; add efficiencies.'],
  },
  'time-distance': {
    concept: 'Distance = speed × time. Trains, boats and races are special cases of relative motion.',
    shortcuts: [
      ['Unit change', 'km/h → m/s: × 5/18. m/s → km/h: × 18/5. (36 km/h = 10 m/s, 54 = 15, 72 = 20, 90 = 25.)'],
      ['Average speed (equal distances)', '2xy/(x + y).'],
      ['Relative speed', 'Same direction: difference of speeds. Opposite directions: sum.'],
      ['Trains', 'Crossing a pole/person: distance = train length. Crossing a platform/train: distance = sum of lengths.'],
      ['Boats', 'Downstream = B + S, upstream = B − S. Boat speed = (D + U)/2, stream speed = (D − U)/2.'],
      ['Inverse ratio', 'For a fixed distance, time ratio is the inverse of speed ratio.'],
    ],
    formulas: ['Speed = distance/time', 'Time to cross = (L₁ + L₂)/relative speed'],
    quick: ['Convert all units first.', 'Decide which distance is covered (lengths added?).', 'Decide which speed applies (relative?).'],
    traps: ['Average speed is NOT (x + y)/2 when distances are equal.'],
  },
  ages: {
    concept: 'Age problems are linear equations; the difference between two people’s ages never changes.',
    shortcuts: [
      ['Ratio multiplier', 'Write present ages as ax and bx, then shift both by the same number of years.'],
      ['Constant difference', 'Age difference stays the same — use it when one person’s age is given at another time.'],
      ['Sum shift', 'n years ago, the sum of two ages was 2n less; after n years it will be 2n more.'],
    ],
    formulas: ['(ax + n)/(bx + n) = c/d ⇒ x = n(d − c)/(bc − ad)'],
    quick: ['Assign x to the present age(s).', 'Shift every age to the time mentioned.', 'Make one equation.'],
    traps: ['Answer the age at the time asked (present, past or future).'],
  },
  'mixture-alligation': {
    concept: 'Alligation finds the ratio in which two ingredients at different prices/concentrations must be mixed to reach a mean value.',
    shortcuts: [
      ['Alligation cross', 'Quantity of cheaper : quantity of dearer = (dearer − mean) : (mean − cheaper).'],
      ['Repeated replacement', 'After removing x litres from V litres and replacing with water n times: pure liquid left = V(1 − x/V)ⁿ.'],
      ['Adding one component', 'The other component stays fixed — use it as the anchor to find the new total.'],
    ],
    formulas: ['Mean price = (q₁p₁ + q₂p₂)/(q₁ + q₂)'],
    quick: ['Write cheaper, dearer and mean values.', 'Cross-subtract to get the ratio.'],
    traps: ['Alligation gives a RATIO; multiply by the total to get quantities.'],
  },
  partnership: {
    concept: 'Partners share profit in the ratio of (capital × time).',
    shortcuts: [
      ['Capital × months', 'Profit ratio = C₁T₁ : C₂T₂. If both invest for the same time, use capitals only.'],
      ['Changing capital', 'Split the year into periods and add capital × months for each period.'],
      ['Working partner', 'Subtract the working partner’s salary/commission first, then share the rest.'],
    ],
    formulas: ['Share = total profit × (own C × T)/(sum of C × T)'],
    quick: ['Make the C × T ratio.', 'Simplify it.', 'Divide the profit.'],
    traps: ['A partner who joins after k months invests for (12 − k) months in a year.'],
  },
  'data-interpretation': {
    concept: 'Read data from a table/graph/chart and answer calculation questions quickly and accurately.',
    shortcuts: [
      ['Read units first', 'Check “in thousands”, “in ₹ crore”, “%” before answering.'],
      ['Percentage change', '(new − old)/old × 100 — the base is always the earlier/compared value.'],
      ['Pie charts', '100% = 360°, so 1% = 3.6°.'],
      ['Compare fractions fast', 'To compare a/b and c/d, compare ad and bc.'],
      ['Approximate when options are far apart', 'Round values to 2 significant figures.'],
    ],
    formulas: ['Average = total/number of items', 'Ratio = a : b simplified by HCF', 'Share in % = part/total × 100'],
    quick: ['Read the title, axes and units.', 'Find only the values each question needs.', 'Simplify before multiplying.'],
    traps: ['“Percentage of” vs “percentage more than” use different formulas.'],
  },
  mensuration: {
    concept: 'Area, perimeter and volume of basic 2-D and 3-D figures.',
    shortcuts: [
      ['Use π = 22/7 when the radius is a multiple of 7', 'Radius 7 → area 154, circumference 44.'],
      ['Percentage change in area', 'If every side changes by x%, area changes by 2x + x²/100 %.'],
      ['Square from diagonal', 'Area = d²/2.'],
    ],
    formulas: ['Rectangle: area lb, perimeter 2(l + b)', 'Square: area a², diagonal a√2', 'Triangle: ½ × base × height; equilateral (√3/4)a²', 'Circle: area πr², circumference 2πr', 'Cuboid lbh; cube a³; cylinder πr²h; cone ⅓πr²h; sphere 4/3 πr³'],
    quick: ['Draw the figure.', 'Write the formula.', 'Substitute with consistent units.'],
    traps: ['Perimeter of a semicircle = πr + 2r, not just πr.'],
  },
}
