// Reasoning topic guides. Shape: { concept, shortcuts: [[title, detail]], formulas (rules), quick, traps }

export default {
  inequality: {
    concept: 'Combine given relations (>, <, ≥, ≤, =) to decide whether a conclusion between two elements is definitely true.',
    shortcuts: [
      ['Read only the path between the two elements', 'Ignore everything outside the chain linking the two letters in the conclusion.'],
      ['Same direction = relation exists', 'If every sign on the path points the same way (>, ≥, = or <, ≤, =), a relation exists. One opposite sign anywhere → no relation.'],
      ['Strongest sign wins', 'Any “>” on the path makes the result “>”; all “=” gives “=”; otherwise “≥”.'],
      ['Either–or test', 'Both conclusions false + same two elements + together they make “≥” (> and =) or “≤” (< and =) → “Either I or II”.'],
      ['Coded inequality', 'Decode the symbols once into a small table, rewrite the statement with real signs, then solve.'],
    ],
    formulas: ['A > B ≥ C ⇒ A > C', 'A ≥ B = C ⇒ A ≥ C', 'A > B < C ⇒ no relation between A and C'],
    quick: ['Rewrite the statements as one chain.', 'Check each conclusion along its path.', 'Apply the either–or test if both fail.'],
    traps: ['“A ≥ B” does not make “A > B” true.'],
  },
  syllogism: {
    concept: 'Decide which conclusions must follow from the statements, using Venn diagrams of all possible cases.',
    shortcuts: [
      ['Two-statement rules', 'All + All = All; All + No = No; Some + All = Some; Some + No = Some-not (“Some A are not C”); No + All (reversed) = “Some C are not A”. Some + Some and Some-not combinations give no definite conclusion.'],
      ['Conversion', '“All A are B” ⇒ “Some B are A”. “Some A are B” ⇔ “Some B are A”. “No A is B” ⇔ “No B is A”. “Some A are not B” cannot be converted.'],
      ['Possibility', 'A possibility follows if it is not contradicted by the statements. “All A being B is a possibility” fails if “No A is B” or “Some A are not B” is definite.'],
      ['Either–or', 'Two conclusions on the same pair, neither definite, forming “Some/No” or “All/Some-not” → Either I or II follows.'],
    ],
    formulas: ['Draw the minimum (basic) diagram first, then test whether any other valid diagram breaks the conclusion.'],
    quick: ['Draw basic diagram.', 'Check definite conclusions.', 'Check possibilities.', 'Check either–or pairs last.'],
    traps: ['Do not use real-world knowledge — only the statements.'],
  },
  'coding-decoding': {
    concept: 'Find the rule that converts a word/number into a code and apply it to a new word.',
    shortcuts: [
      ['EJOTY', 'E = 5, J = 10, O = 15, T = 20, Y = 25 — find any letter’s position in seconds.'],
      ['Opposite letters', 'Opposite pairs add to 27: A↔Z, B↔Y, C↔X … M↔N.'],
      ['Check in this order', '1) constant shift (+1, −2), 2) reversed word, 3) opposite letters, 4) position sums/products.'],
      ['First and last letters', 'Compare the first and last letters of word and code to detect reversal quickly.'],
      ['Sentence codes', 'A word common to two sentences has the code common to both; three-way overlaps fix a word uniquely.'],
    ],
    formulas: ['Opposite letter = 27 − position', 'Position from Z end = 27 − position from A end'],
    quick: ['Write positions above the given word and code.', 'Find the rule.', 'Apply it to the new word.'],
    traps: ['A shift can wrap around: Z + 1 = A.'],
  },
  'blood-relations': {
    concept: 'Work out family relationships from statements and represent them in a family tree.',
    shortcuts: [
      ['Standard symbols', '+ male, − female, = married couple, | parent–child (vertical), — siblings (horizontal).'],
      ['Generation count', 'Grandparents are 2 levels up, children 1 level down. Same level → sibling, cousin, spouse or in-law.'],
      ['Start from the end', 'In “my father’s sister’s son” start at the speaker and move one relation at a time.'],
      ['Only son / only daughter', '“Only son of my father/mother” (said by a male) is the speaker himself.'],
      ['Coded relations', 'Translate each code into a word first, then draw the tree.'],
    ],
    formulas: ['Father’s/mother’s brother = uncle; their sister = aunt.', 'Brother’s/sister’s son = nephew; daughter = niece.', 'Spouse’s parent = parent-in-law; sibling’s spouse or spouse’s sibling = brother/sister-in-law.'],
    quick: ['Draw the tree as you read.', 'Mark genders the moment they are known.', 'Answer from the person asked about.'],
    traps: ['Never assume gender from a name.'],
  },
  'direction-sense': {
    concept: 'Track a person’s movements and turns to find final position, distance and direction.',
    shortcuts: [
      ['Turns', 'Right turn = 90° clockwise; left turn = 90° anticlockwise. Two right turns reverse the direction.'],
      ['Net displacement', 'Add all East–West moves and all North–South moves separately, then combine.'],
      ['Pythagorean triples', '3-4-5, 6-8-10, 5-12-13, 8-15-17, 7-24-25.'],
      ['Shadows', 'Morning: sun in the East, shadow falls West. Evening: sun in the West, shadow falls East.'],
    ],
    formulas: ['Shortest distance = √(x² + y²)'],
    quick: ['Draw axes.', 'Plot each move.', 'Compute net x and y.', 'Name the direction from start to end.'],
    traps: ['“Direction of A from B” is measured standing at B.'],
  },
  'order-ranking': {
    concept: 'Positions of people in a row or a ranking list from either end.',
    shortcuts: [
      ['Total', 'Total = rank from left + rank from right − 1.'],
      ['Persons between (no overlap)', 'Between = Total − (A’s rank from left + B’s rank from right).'],
      ['Persons between (overlap)', 'If the positions overlap: Between = (L + R) − Total − 2.'],
      ['Interchange', 'After swapping, the person’s new position equals the other person’s old position — combine it with the other end to get the total.'],
    ],
    formulas: ['Position from right = Total − position from left + 1'],
    quick: ['Convert every rank to “from left”.', 'Subtract positions to count people between.'],
    traps: ['Failed/absent students are added after counting passed students.'],
  },
  'alphanumeric-series': {
    concept: 'Questions on a mixed series of letters, digits and symbols.',
    shortcuts: [
      ['Same-side rule', 'k-th to the right of the m-th from the left = (m + k)-th from the left.'],
      ['Opposite-side rule', 'k-th to the left of the m-th from the left = (m − k)-th from the left.'],
      ['Convert ends', 'm-th from the right = (Total − m + 1)-th from the left.'],
      ['Counting conditions', 'For “immediately preceded by X and followed by Y”, scan only the middle element type, then check its two neighbours.'],
    ],
    formulas: ['Element position from left + position from right = Total + 1'],
    quick: ['Number the series once.', 'Use position rules instead of counting each time.'],
    traps: ['After removing elements, re-number the remaining series.'],
  },
  'linear-seating': {
    concept: 'Place people in a row using the clues so that exactly one arrangement satisfies all of them.',
    shortcuts: [
      ['Facing direction', 'Facing North: their right = your right. Facing South: their right = your left.'],
      ['Start with fixed clues', 'Ends, exact positions and “immediate” neighbours first; vague clues (“somewhere to the left”) last.'],
      ['Cases', 'When a clue allows two placements, draw both cases side by side and eliminate with later clues.'],
      ['“Only k between”', 'Positions differ by k + 1.'],
    ],
    formulas: ['In a row of n, the middle position is (n + 1)/2 for odd n.'],
    quick: ['Draw n blanks.', 'Place definite people.', 'Branch into cases.', 'Eliminate with negative clues.'],
    traps: ['“Second to the left” ≠ “second from the left end”.'],
  },
  'circular-seating': {
    concept: 'Arrange people around a table; there are no ends, so positions are relative.',
    shortcuts: [
      ['Facing the centre', 'Left = clockwise, right = anticlockwise. Facing outside: reversed.'],
      ['Fix one person', 'Place any definite person first; rotations of the same circle are identical.'],
      ['Left ↔ right conversion', 'In a circle of n, k-th to the left = (n − k)-th to the right.'],
      ['Opposite seats', 'With n even, the opposite person is n/2 seats away.'],
    ],
    formulas: ['Number of persons between X and Y (one way) = seats apart − 1'],
    quick: ['Draw n points.', 'Fix the most-referenced person.', 'Place relative clues around them.'],
    traps: ['Mixed facing: check each person’s facing before applying left/right.'],
  },
  'floor-puzzle': {
    concept: 'Assign people (and attributes) to floors of a building.',
    shortcuts: [
      ['Numbering', 'Floor 1 is the lowest unless stated otherwise.'],
      ['Above vs immediately above', '“Above” = any higher floor; “immediately above” = next floor.'],
      ['Gaps', '“Only two people between” = floors differ by 3.'],
      ['Odd/even clues', 'Use parity clues to cut cases early.'],
    ],
    formulas: ['Floors between X and Y = |difference| − 1'],
    quick: ['Draw floors top to bottom.', 'Place definite floors.', 'Use gaps/parity to fix the rest.'],
    traps: ['Some puzzles number the top floor as 1 — read the first line.'],
  },
  'box-puzzle': {
    concept: 'Boxes stacked one above another; same logic as floor puzzles with box attributes.',
    shortcuts: [
      ['Gaps', '“Two boxes between” = positions differ by 3.'],
      ['Count from both ends', '“Third from the top” in 7 boxes = 5th from the bottom.'],
      ['Attribute table', 'Keep a side table for colours/items so each box’s attributes stay linked.'],
    ],
    formulas: ['Position from top = Total − position from bottom + 1'],
    quick: ['Draw the stack.', 'Place definite boxes.', 'Branch cases for “between” clues.'],
    traps: ['“Above” does not mean “immediately above”.'],
  },
  'scheduling-puzzle': {
    concept: 'Arrange events in days of a week, months of a year or dates of a month.',
    shortcuts: [
      ['Months with 31 days', 'January, March, May, July, August, October, December. 30 days: April, June, September, November.'],
      ['Before/after ranges', 'Turn “before X” into a range of possible positions and intersect ranges.'],
      ['Two dates per month', 'When each month has two dates (e.g. 8th and 19th), treat each month as two ordered slots.'],
    ],
    formulas: ['Events between X and Y = slot difference − 1'],
    quick: ['List the slots in order.', 'Place fixed days.', 'Fill with relative clues.'],
    traps: ['A week in the puzzle may start on Monday, not Sunday — check the first line.'],
  },
  'misc-puzzles': {
    concept: 'Comparison, grouping and multi-variable puzzles.',
    shortcuts: [
      ['Comparison chain', 'Write a single chain such as A > C > B and insert each new person as you read.'],
      ['Grid elimination', 'For person × attribute puzzles, draw a table and mark ✓/✗; a row with one blank left is fixed.'],
      ['Group by attribute', 'When each group has a fixed size, fill the group with the most constraints first.'],
    ],
    formulas: ['“Only k taller than X” ⇒ X is (k + 1)-th tallest'],
    quick: ['Choose chain or grid.', 'Fill definite clues.', 'Eliminate.'],
    traps: ['“Not the tallest” still allows second-tallest.'],
  },
  'misc-reasoning': {
    concept: 'Short questions on analogy, classification, letter series, word formation and logical reasoning.',
    shortcuts: [
      ['Letter series', 'Write positions (EJOTY) and look at the gaps between letters.'],
      ['Odd one out', 'Check gaps between letters, vowels, squares/cubes/primes, or sum of digits.'],
      ['Letter pairs in a word', 'Count pairs that have as many letters between them in the word as in the alphabet — check both forward and backward.'],
      ['Number analogy', 'Test n², n³, n² ± 1, n(n + 1) on the first pair before the second.'],
    ],
    formulas: ['Common relations: n², n³, n² ± 1, n³ ± 1, n(n + 1)'],
    quick: ['Find the relation on the given pair.', 'Apply it to the second pair.'],
    traps: ['The relation must work for the given pair exactly, not approximately.'],
  },
}
